services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: "wakapi"
      POSTGRES_DB: "wakapi"
      PGPORT: 55432
    network_mode: host

  mysql:
    image: mysql:8
    environment:
      MYSQL_TCP_PORT: 53306
      MYSQL_USER: "wakapi"
      MYSQL_PASSWORD: "wakapi"
      MYSQL_DATABASE: "wakapi"
      MYSQL_ROOT_PASSWORD: example
    network_mode: host

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_TCP_PORT: 53306
      MARIADB_USER: "wakapi"
      MARIADB_PASSWORD: "wakapi"
      MARIADB_DATABASE: "wakapi"
      MARIADB_ROOT_PASSWORD: example
    network_mode: host
